In [6]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, date
import matplotlib.pyplot as plt

In [7]:
lmh_values = ['low', 'high', 'medium', 'medium', 'high']
lmh_cat = pd.Categorical(lmh_values)
lmh_cat

[low, high, medium, medium, high]
Categories (3, object): [high, low, medium]

In [8]:
lmh_cat.categories

Index(['high', 'low', 'medium'], dtype='object')

In [11]:
lmh_cat.to_numpy()

array(['low', 'high', 'medium', 'medium', 'high'], dtype=object)

In [12]:
lmh_cat.codes

array([1, 0, 2, 2, 0], dtype=int8)

In [13]:
lmh_cat = pd.Categorical(lmh_values, categories=['low', 'medium', 'high'])
lmh_cat

[low, high, medium, medium, high]
Categories (3, object): [low, medium, high]

In [14]:
lmh_cat.codes

array([0, 2, 1, 1, 2], dtype=int8)

In [15]:
lmh_cat.sort_values()

[low, medium, medium, high, high]
Categories (3, object): [low, medium, high]

In [16]:
cat_series = pd.Series(lmh_values, dtype='category')
cat_series

0       low
1      high
2    medium
3    medium
4      high
dtype: category
Categories (3, object): [high, low, medium]

In [17]:
s = pd.Series(lmh_values)
as_cat = s.astype('category')
cat_series

0       low
1      high
2    medium
3    medium
4      high
dtype: category
Categories (3, object): [high, low, medium]

In [18]:
cat_series.cat

In [19]:
cat_series.cat.categories

Index(['high', 'low', 'medium'], dtype='object')

In [20]:
np.random.seed(123456)
values = np.random.randint(0, 100, 5)
bins = pd.DataFrame({'values' : values})
bins

values
0      65
1      49
2      56
3      43
4      43

In [21]:
bins['Group'] = pd.cut(values, range(0, 101, 10))
bins

values     Group
0      65  (60, 70]
1      49  (40, 50]
2      56  (50, 60]
3      43  (40, 50]
4      43  (40, 50]

In [22]:
bins.Group

0    (60, 70]
1    (40, 50]
2    (50, 60]
3    (40, 50]
4    (40, 50]
Name: Group, dtype: category
Categories (10, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [23]:
metal_values = ['bronze', 'gold', 'silver', 'bronze']
metal_categories = ['bronze', 'silver', 'gold']
metals = pd.Categorical(metal_values, categories = metal_categories, ordered= True)
metals

[bronze, gold, silver, bronze]
Categories (3, object): [bronze < silver < gold]

In [26]:
metal_reversed_values = pd.Categorical(metals.to_numpy()[::-1], categories= metals.categories, ordered=True)
metal_reversed_values

[bronze, silver, gold, bronze]
Categories (3, object): [bronze < silver < gold]

In [27]:
metals <= metal_reversed_values

array([ True, False,  True,  True])

In [28]:
metals.codes

array([0, 2, 1, 0], dtype=int8)

In [29]:
metal_reversed_values.codes

array([0, 1, 2, 0], dtype=int8)

In [30]:
pd.Categorical(['bronze', 'copper'], categories=metal_categories)

[bronze, NaN]
Categories (3, object): [bronze, silver, gold]

In [31]:
cat = pd.Categorical(['a', 'b', 'c', 'a'], categories=['a', 'b', 'c'])
cat

[a, b, c, a]
Categories (3, object): [a, b, c]

In [32]:
cat.categories = ['bronze', 'silver', 'gold']
cat

[bronze, silver, gold, bronze]
Categories (3, object): [bronze, silver, gold]