In [1]:
import tensorflow as tf
import datetime
import keras
from keras import layers, Input
from keras.models import Model
import numpy as np
import pandas as pd
#from tensorflow.keras import datasets, layers, models, optimizers
%load_ext tensorboard



Using TensorFlow backend.


In [2]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [3]:
train

id  digit letter  0  1  2  3  4  5  6  ...  774  775  776  777  778  \
0        1      5      L  1  1  1  4  3  0  0  ...    2    1    0    1    2   
1        2      0      B  0  4  0  0  4  1  1  ...    0    3    0    1    4   
2        3      4      L  1  1  2  2  1  1  1  ...    3    3    3    0    2   
3        4      9      D  1  2  0  2  0  4  0  ...    3    3    2    0    1   
4        5      6      A  3  0  2  4  0  3  0  ...    4    4    3    2    1   
...    ...    ...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
2043  2044      6      V  2  4  3  4  2  4  4  ...    0    2    2    0    0   
2044  2045      1      L  3  2  2  1  1  4  0  ...    2    3    4    2    1   
2045  2046      9      A  4  0  4  0  2  4  4  ...    2    3    1    1    3   
2046  2047      0      Z  2  3  3  0  3  0  4  ...    2    3    1    1    0   
2047  2048      5      Z  4  2  2  1  3  0  0  ...    4    2    4    0    4   

      779  780  781  782  783  
0       4    4    4    3    4  
1       1    4    2    1    2  
2       0    3    0    2    2  
3       4    0    0    1    1  
4       3    4    3    1    2  
...   ...  ...  ...  ...  ...  
2043    1    3    1    4    0  
2044    2    3    4    1    1  
2045    4    2    2    0    0  
2046    4    1    4    3    1  
2047    3    2    4    3    4  

[2048 rows x 787 columns]

In [4]:
aa = train.copy()
aa

id  digit letter  0  1  2  3  4  5  6  ...  774  775  776  777  778  \
0        1      5      L  1  1  1  4  3  0  0  ...    2    1    0    1    2   
1        2      0      B  0  4  0  0  4  1  1  ...    0    3    0    1    4   
2        3      4      L  1  1  2  2  1  1  1  ...    3    3    3    0    2   
3        4      9      D  1  2  0  2  0  4  0  ...    3    3    2    0    1   
4        5      6      A  3  0  2  4  0  3  0  ...    4    4    3    2    1   
...    ...    ...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
2043  2044      6      V  2  4  3  4  2  4  4  ...    0    2    2    0    0   
2044  2045      1      L  3  2  2  1  1  4  0  ...    2    3    4    2    1   
2045  2046      9      A  4  0  4  0  2  4  4  ...    2    3    1    1    3   
2046  2047      0      Z  2  3  3  0  3  0  4  ...    2    3    1    1    0   
2047  2048      5      Z  4  2  2  1  3  0  0  ...    4    2    4    0    4   

      779  780  781  782  783  
0       4    4    4    3    4  
1       1    4    2    1    2  
2       0    3    0    2    2  
3       4    0    0    1    1  
4       3    4    3    1    2  
...   ...  ...  ...  ...  ...  
2043    1    3    1    4    0  
2044    2    3    4    1    1  
2045    4    2    2    0    0  
2046    4    1    4    3    1  
2047    3    2    4    3    4  

[2048 rows x 787 columns]

In [5]:
letter = aa['letter']
test_letter = test['letter']
letter = letter.to_frame()
test_letter = test_letter.to_frame()

In [6]:
ytrain = aa['digit']
ytrain = ytrain.to_frame()
ytrain

digit
0         5
1         0
2         4
3         9
4         6
...     ...
2043      6
2044      1
2045      9
2046      0
2047      5

[2048 rows x 1 columns]

In [7]:
xtrain = aa.drop(['id', 'digit', 'letter'], axis = 1)
test = test.drop(['id', 'letter'], axis = 1)

In [8]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [9]:
onehot_ytrain = encoder.fit_transform(ytrain)
onehot_letter = encoder.fit_transform(letter)
onehot_test_letter = encoder.fit_transform(test_letter)

onehot_ytrain = onehot_ytrain.toarray()
onehot_letter = onehot_letter.toarray()
onehot_test_letter = onehot_test_letter.toarray()

print(onehot_ytrain)
print(onehot_letter)
print(onehot_test_letter)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
# digit  디코딩
decoding = np.argmax(onehot_ytrain, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0         5
1         0
2         4
3         9
4         6
...     ...
2043      6
2044      1
2045      9
2046      0
2047      5

[2048 rows x 1 columns]

In [11]:
xtrain /= 255.0
test /= 255.0

xtrain = np.array(xtrain)
test = np.array(test)

print(xtrain.shape)
print(test.shape)

(2048, 784)
(20480, 784)


In [12]:
print(xtrain.shape)
print(onehot_ytrain.shape)
print(onehot_letter.shape)

(2048, 784)
(2048, 10)
(2048, 26)


In [13]:
xtrain = xtrain.reshape((2048, 28, 28, 1))
test = test.reshape((20480, 28, 28, 1))
onehot_letter = onehot_letter.reshape((2048, 1, 26))
onehot_test_letter = onehot_test_letter.reshape((20480, 1, 26))

xtrain = xtrain.astype('float32')
test = test.astype('float32')
onehot_letter = onehot_letter.astype('float32')
onehot_test_letter = onehot_test_letter.astype('float32')

In [14]:
print(xtrain.shape)
print(test.shape)
print(onehot_letter.shape)
print(onehot_test_letter.shape)

(2048, 28, 28, 1)
(20480, 28, 28, 1)
(2048, 1, 26)
(20480, 1, 26)


In [15]:
# from tensorflow.keras.preprocessing.image import ImageDataGenerator

# datagen = ImageDataGenerator(
#     rotation_range = 90,
# )
# datagen.fit(xtrain)

In [16]:
image_input = Input(shape = (28, 28, 1), dtype = 'float32', name = 'image')
letter_input = Input(shape = (1, 26), dtype = 'float32', name = 'letter')

In [23]:

cnn = layers.ZeroPadding2D((2, 2))(image_input)
cnn = layers.Conv2D(128, (3, 3), activation = 'relu', padding = 'same')(cnn)
cnn = layers.Conv2D(128, (3, 3), activation = 'relu')(cnn)
cnn = layers.MaxPooling2D(2, 2)(cnn)
cnn = layers.ZeroPadding2D((2, 2))(cnn)
cnn = layers.Conv2D(256, (3, 3), activation = 'relu', padding = 'same')(cnn)
cnn = layers.Conv2D(256, (3, 3), activation = 'relu')(cnn)
cnn = layers.MaxPooling2D(2, 2)(cnn)
cnn = layers.Dropout(0.2)(cnn)
cnn = layers.Flatten()(cnn)


dnn = layers.LSTM(128, activation = 'relu', return_sequences = True)(letter_input)
dnn = layers.LSTM(256, activation = 'relu')(dnn)


concatenated = layers.concatenate([cnn, dnn])

result = layers.Dense(256, activation = 'relu')(concatenated)
result = layers.Dropout(0.5)(result)
result = layers.Dense(10, activation = 'softmax')(result)

model = Model([image_input, letter_input], result)
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
image (InputLayer)              [(None, 28, 28, 1)]  0                                            
__________________________________________________________________________________________________
zero_padding2d_2 (ZeroPadding2D (None, 32, 32, 1)    0           image[0][0]                      
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 32, 32, 128)  1280        zero_padding2d_2[0][0]           
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 30, 30, 128)  147584      conv2d_4[0][0]                   
____________________________________________________________________________________________

In [18]:
# OPTIMIZER = tf.keras.optimizers.Adamax(0.1)
# OPTIMIZER = tf.keras.optimizers.RMSprop(0.01)
# OPTIMIZER = tf.keras.optimizers.SGD(0.1)
# OPTIMIZER = tf.keras.optimizers.Adagrad(0.01)
OPTIMIZER = tf.keras.optimizers.Adam(0.001)

In [19]:
EarlyStopping = tf.keras.callbacks.EarlyStopping(monitor = 'val_accuracy', patience = 10)
ModelCheckpoint = tf.keras.callbacks.ModelCheckpoint(filepath = 'best_model.h5', monitor = 'val_loss', save_weights_only = True, save_best_only = True)
ReduceLROnPlateau = tf.keras.callbacks.ReduceLROnPlateau(monitor = 'val_loss', patience = 5, factor = 0.1)

In [20]:
model.compile(optimizer = OPTIMIZER,
                loss = 'categorical_crossentropy',
                metrics = ["accuracy"])

In [21]:
model.fit(
    {'image' : xtrain, 'letter' : onehot_letter}, onehot_ytrain,
    batch_size = 32,
    epochs = 150,
    verbose = 1,
    validation_split = 0.10,
    callbacks = [EarlyStopping, ModelCheckpoint, ReduceLROnPlateau]
)

Epoch 1/150
 4/58 [=>............................] - ETA: 18s - loss: 3.6898 - accuracy: 0.1562

KeyboardInterrupt: 

[Tensorboard Link](http://localhost:6006)  
71/71 [==============================] - 13s 181ms/step - loss: 0.0737 - accuracy: 0.9756 - val_loss: 0.5013 - val_accuracy: 0.8244  85%

Epoch 11/150
58/58 [==============================] - 18s 316ms/step - loss: 0.2306 - accuracy: 0.9143 - val_loss: 0.4259 - val_accuracy: 0.8585 - lr: 0.0010 87%

In [22]:
y_pred = model.predict({'image' : test, 'letter' : onehot_test_letter}, batch_size=32)
# # digit  디코딩
# decoding = np.argmax(y_pred, axis=1).reshape(-1,1)
# decoding = pd.DataFrame(decoding, columns = ['digit'])
# decoding

In [23]:
decoding = np.argmax(y_pred, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0          6
1          9
2          8
3          0
4          3
...      ...
20475      4
20476      1
20477      6
20478      1
20479      0

[20480 rows x 1 columns]

In [24]:
sorted(decoding['digit'].unique())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
model.load_weights('best_model87.h5')
y_pred = model.predict({'image' : test, 'letter' : onehot_test_letter}, batch_size=32)
# digit  디코딩
decoding = np.argmax(y_pred, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0          6
1          9
2          8
3          0
4          3
...      ...
20475      4
20476      1
20477      6
20478      1
20479      0

[20480 rows x 1 columns]

In [32]:
sub = pd.read_csv('data/submission.csv')
sub = sub.drop(['digit'], axis = 1)
sub = pd.concat([sub, decoding], axis = 1)
sub.to_csv('sub.csv', index = False, encoding = 'utf-8')
sub

id  digit
0       2049      6
1       2050      9
2       2051      8
3       2052      0
4       2053      3
...      ...    ...
20475  22524      4
20476  22525      1
20477  22526      6
20478  22527      1
20479  22528      0

[20480 rows x 2 columns]