In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras import datasets, layers, models, optimizers

In [2]:
(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

In [3]:
# 크기 조정
X_train = X_train.reshape((60000, 28, 28, 1))
X_test = X_test.reshape((10000, 28, 28, 1))

In [4]:
# 정규화
X_train, X_test = X_train / 255, X_test / 255

In [5]:
# 형식 변환
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [6]:
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [7]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [8]:
OPTIMIZER = tf.keras.optimizers.Adam()
EPOCHS = 5
BATCH_SIZE = 128
VERBOSE = 1
VALIDATION_SPLIT = 0.95

IMG_ROWS, IMG_COLS = 28,28
INPUT_SHAPE = (IMG_ROWS, IMG_COLS, 1)
NB_CLASSES = 10

In [9]:
def build(input_shape, classes):
    model = models.Sequential()
    model.add(layers.Convolution2D(20, (5, 5), activation = 'relu', input_shape = input_shape))
    model.add(layers.MaxPooling2D(pool_size = (2, 2), strides = (2, 2)))
    model.add(layers.Convolution2D(50, (5, 5), activation = 'relu'))
    model.add(layers.MaxPooling2D(pool_size = (2, 2), strides = (2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(500, activation = 'relu'))
    model.add(layers.Dense(classes, activation = 'softmax'))
    
    return model


In [10]:
model = build(input_shape = (28, 28, 1), classes = 10)
model.compile(optimizer = OPTIMIZER, loss = 'categorical_crossentropy', metrics = ["accuracy"])
model.summary()

callbacks = [tf.keras.callbacks.TensorBoard(log_dir = './logs')]

history = model.fit(X_train, y_train,
                    batch_size = BATCH_SIZE,
                    epochs = 5,
                    verbose = 1,
                    validation_split = 0.95,
                    callbacks = callbacks)

score = model.evaluate(X_test, y_test, verbose = 1)

print("\nTest score:", score[0])
print('Test accuracy', score[1])


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 24, 20)        520       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 20)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 8, 50)          25050     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 4, 50)          0         
_________________________________________________________________
flatten (Flatten)            (None, 800)               0         
_________________________________________________________________
dense (Dense)                (None, 500)               400500    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5

In [11]:
train = pd.read_csv('data/train.csv')

In [12]:
train

id  digit letter  0  1  2  3  4  5  6  ...  774  775  776  777  778  \
0        1      5      L  1  1  1  4  3  0  0  ...    2    1    0    1    2   
1        2      0      B  0  4  0  0  4  1  1  ...    0    3    0    1    4   
2        3      4      L  1  1  2  2  1  1  1  ...    3    3    3    0    2   
3        4      9      D  1  2  0  2  0  4  0  ...    3    3    2    0    1   
4        5      6      A  3  0  2  4  0  3  0  ...    4    4    3    2    1   
...    ...    ...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
2043  2044      6      V  2  4  3  4  2  4  4  ...    0    2    2    0    0   
2044  2045      1      L  3  2  2  1  1  4  0  ...    2    3    4    2    1   
2045  2046      9      A  4  0  4  0  2  4  4  ...    2    3    1    1    3   
2046  2047      0      Z  2  3  3  0  3  0  4  ...    2    3    1    1    0   
2047  2048      5      Z  4  2  2  1  3  0  0  ...    4    2    4    0    4   

      779  780  781  782  783  
0       4    4    4    3    4  
1       1    4    2    1    2  
2       0    3    0    2    2  
3       4    0    0    1    1  
4       3    4    3    1    2  
...   ...  ...  ...  ...  ...  
2043    1    3    1    4    0  
2044    2    3    4    1    1  
2045    4    2    2    0    0  
2046    4    1    4    3    1  
2047    3    2    4    3    4  

[2048 rows x 787 columns]

In [13]:
aa = train.copy()
aa

id  digit letter  0  1  2  3  4  5  6  ...  774  775  776  777  778  \
0        1      5      L  1  1  1  4  3  0  0  ...    2    1    0    1    2   
1        2      0      B  0  4  0  0  4  1  1  ...    0    3    0    1    4   
2        3      4      L  1  1  2  2  1  1  1  ...    3    3    3    0    2   
3        4      9      D  1  2  0  2  0  4  0  ...    3    3    2    0    1   
4        5      6      A  3  0  2  4  0  3  0  ...    4    4    3    2    1   
...    ...    ...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
2043  2044      6      V  2  4  3  4  2  4  4  ...    0    2    2    0    0   
2044  2045      1      L  3  2  2  1  1  4  0  ...    2    3    4    2    1   
2045  2046      9      A  4  0  4  0  2  4  4  ...    2    3    1    1    3   
2046  2047      0      Z  2  3  3  0  3  0  4  ...    2    3    1    1    0   
2047  2048      5      Z  4  2  2  1  3  0  0  ...    4    2    4    0    4   

      779  780  781  782  783  
0       4    4    4    3    4  
1       1    4    2    1    2  
2       0    3    0    2    2  
3       4    0    0    1    1  
4       3    4    3    1    2  
...   ...  ...  ...  ...  ...  
2043    1    3    1    4    0  
2044    2    3    4    1    1  
2045    4    2    2    0    0  
2046    4    1    4    3    1  
2047    3    2    4    3    4  

[2048 rows x 787 columns]

In [14]:
ytrain = aa['digit']
ytrain = ytrain.to_frame()
ytrain

digit
0         5
1         0
2         4
3         9
4         6
...     ...
2043      6
2044      1
2045      9
2046      0
2047      5

[2048 rows x 1 columns]

In [15]:
xtrain = aa.drop(['id', 'digit', 'letter'], axis = 1)
xtrain

0  1  2  3  4  5  6  7  8  9  ...  774  775  776  777  778  779  780  \
0     1  1  1  4  3  0  0  4  4  3  ...    2    1    0    1    2    4    4   
1     0  4  0  0  4  1  1  1  4  2  ...    0    3    0    1    4    1    4   
2     1  1  2  2  1  1  1  0  2  1  ...    3    3    3    0    2    0    3   
3     1  2  0  2  0  4  0  3  4  3  ...    3    3    2    0    1    4    0   
4     3  0  2  4  0  3  0  4  2  4  ...    4    4    3    2    1    3    4   
...  .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
2043  2  4  3  4  2  4  4  1  2  1  ...    0    2    2    0    0    1    3   
2044  3  2  2  1  1  4  0  1  4  2  ...    2    3    4    2    1    2    3   
2045  4  0  4  0  2  4  4  4  3  4  ...    2    3    1    1    3    4    2   
2046  2  3  3  0  3  0  4  3  0  1  ...    2    3    1    1    0    4    1   
2047  4  2  2  1  3  0  0  0  3  2  ...    4    2    4    0    4    3    2   

      781  782  783  
0       4    3    4  
1       2    1    2  
2       0    2    2  
3       0    1    1  
4       3    1    2  
...   ...  ...  ...  
2043    1    4    0  
2044    4    1    1  
2045    2    0    0  
2046    4    3    1  
2047    4    3    4  

[2048 rows x 784 columns]

In [16]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [17]:
ytrain1 = encoder.fit_transform(ytrain)
ytrain1 = ytrain1.toarray()
ytrain1

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
# digit  디코딩
decoding = np.argmax(ytrain1, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0         5
1         0
2         4
3         9
4         6
...     ...
2043      6
2044      1
2045      9
2046      0
2047      5

[2048 rows x 1 columns]

In [19]:
xtrain /= 255
xtrain

0         1         2         3         4         5         6  \
0     0.003922  0.003922  0.003922  0.015686  0.011765  0.000000  0.000000   
1     0.000000  0.015686  0.000000  0.000000  0.015686  0.003922  0.003922   
2     0.003922  0.003922  0.007843  0.007843  0.003922  0.003922  0.003922   
3     0.003922  0.007843  0.000000  0.007843  0.000000  0.015686  0.000000   
4     0.011765  0.000000  0.007843  0.015686  0.000000  0.011765  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
2043  0.007843  0.015686  0.011765  0.015686  0.007843  0.015686  0.015686   
2044  0.011765  0.007843  0.007843  0.003922  0.003922  0.015686  0.000000   
2045  0.015686  0.000000  0.015686  0.000000  0.007843  0.015686  0.015686   
2046  0.007843  0.011765  0.011765  0.000000  0.011765  0.000000  0.015686   
2047  0.015686  0.007843  0.007843  0.003922  0.011765  0.000000  0.000000   

             7         8         9  ...       774       775       776  \
0     0.015686  0.015686  0.011765  ...  0.007843  0.003922  0.000000   
1     0.003922  0.015686  0.007843  ...  0.000000  0.011765  0.000000   
2     0.000000  0.007843  0.003922  ...  0.011765  0.011765  0.011765   
3     0.011765  0.015686  0.011765  ...  0.011765  0.011765  0.007843   
4     0.015686  0.007843  0.015686  ...  0.015686  0.015686  0.011765   
...        ...       ...       ...  ...       ...       ...       ...   
2043  0.003922  0.007843  0.003922  ...  0.000000  0.007843  0.007843   
2044  0.003922  0.015686  0.007843  ...  0.007843  0.011765  0.015686   
2045  0.015686  0.011765  0.015686  ...  0.007843  0.011765  0.003922   
2046  0.011765  0.000000  0.003922  ...  0.007843  0.011765  0.003922   
2047  0.000000  0.011765  0.007843  ...  0.015686  0.007843  0.015686   

           777       778       779       780       781       782       783  
0     0.003922  0.007843  0.015686  0.015686  0.015686  0.011765  0.015686  
1     0.003922  0.015686  0.003922  0.015686  0.007843  0.003922  0.007843  
2     0.000000  0.007843  0.000000  0.011765  0.000000  0.007843  0.007843  
3     0.000000  0.003922  0.015686  0.000000  0.000000  0.003922  0.003922  
4     0.007843  0.003922  0.011765  0.015686  0.011765  0.003922  0.007843  
...        ...       ...       ...       ...       ...       ...       ...  
2043  0.000000  0.000000  0.003922  0.011765  0.003922  0.015686  0.000000  
2044  0.007843  0.003922  0.007843  0.011765  0.015686  0.003922  0.003922  
2045  0.003922  0.011765  0.015686  0.007843  0.007843  0.000000  0.000000  
2046  0.003922  0.000000  0.015686  0.003922  0.015686  0.011765  0.003922  
2047  0.000000  0.015686  0.011765  0.007843  0.015686  0.011765  0.015686  

[2048 rows x 784 columns]

In [20]:
xtrain = np.array(xtrain)

In [21]:
print(xtrain.shape)
print(ytrain1.shape)

(2048, 784)
(2048, 10)


In [22]:
xtrain = xtrain.reshape((2048, 28, 28, 1))
xtrain = xtrain.astype('float32')
ytrain1 = ytrain1.astype('float32')
# ytrain1 = tf.keras.utils.to_categorical(ytrain1, 10)

In [23]:
X_train.shape

(60000, 28, 28, 1)

In [24]:
y_train.shape

(60000, 10)

In [25]:
xtrain.shape

(2048, 28, 28, 1)

In [26]:
ytrain1.shape

(2048, 10)

In [49]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
checkpoint = tf.keras.callbacks.ModelCheckpoint('best_model.h5', monitor='loss', save_weights_only=True, save_best_only=True)

In [47]:
OPTIMIZER = tf.keras.optimizers.Adam(learning_rate = 0.001)
EPOCHS = 5
BATCH_SIZE = 128
VERBOSE = 1
VALIDATION_SPLIT = 0.95

IMG_ROWS, IMG_COLS = 28,28
INPUT_SHAPE = (IMG_ROWS, IMG_COLS, 1)
NB_CLASSES = 10

In [50]:
model = build(input_shape = (28, 28, 1), classes = 10)
model.compile(optimizer = OPTIMIZER, loss = 'categorical_crossentropy', metrics = ["accuracy"])
model.summary()

# callbacks = [tf.keras.callbacks.TensorBoard(log_dir = './logs')]

history = model.fit(xtrain, ytrain1,
                    batch_size = 26,
                    epochs = 30,
                    verbose = 1,
                    validation_split = 0.70,
                    callbacks = [checkpoint])

# score = model.evaluate(X_test, y_test, verbose = 1)

# print("\nTest score:", score[0])
# print('Test accuracy', score[1])

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_26 (Conv2D)           (None, 24, 24, 20)        520       
_________________________________________________________________
max_pooling2d_26 (MaxPooling (None, 12, 12, 20)        0         
_________________________________________________________________
conv2d_27 (Conv2D)           (None, 8, 8, 50)          25050     
_________________________________________________________________
max_pooling2d_27 (MaxPooling (None, 4, 4, 50)          0         
_________________________________________________________________
flatten_13 (Flatten)         (None, 800)               0         
_________________________________________________________________
dense_26 (Dense)             (None, 500)               400500    
_________________________________________________________________
dense_27 (Dense)             (None, 10)              

In [36]:
X_test.shape

(10000, 28, 28, 1)

In [38]:
y_test.shape

(10000, 10)

In [67]:
test = pd.read_csv('data/test.csv')
test = test.drop(['id', 'letter'], axis = 1)
test /= 255
test = np.array(test)
test = test.reshape((20480, 28, 28, 1))
test = test.astype('float32')

In [68]:
test.shape

(20480, 28, 28, 1)

In [69]:
y_pred = model.predict(test, batch_size=1)

In [74]:
y_pred

array([[3.12465991e-11, 3.86841387e-01, 5.22083402e-01, ...,
        8.86976644e-02, 1.25228090e-03, 2.25476018e-04],
       [2.79132023e-10, 4.93204221e-02, 1.85056170e-09, ...,
        8.31396461e-01, 2.59505015e-07, 5.75554091e-03],
       [1.83736178e-04, 9.53978233e-05, 2.95781288e-02, ...,
        1.52375098e-04, 9.45560168e-04, 1.49499596e-04],
       ...,
       [5.03934547e-03, 2.86367641e-09, 9.02133354e-04, ...,
        5.53388779e-10, 7.44770878e-05, 2.27033747e-09],
       [7.66225408e-13, 4.25599664e-02, 1.01680607e-05, ...,
        4.41376433e-05, 8.85134041e-01, 3.39897213e-08],
       [5.94068078e-05, 1.98072980e-09, 5.08116186e-02, ...,
        1.17005765e-08, 4.11414774e-04, 8.13944666e-07]], dtype=float32)

In [72]:
aa = y_pred * 255
aa 

array([[7.9678824e-09, 9.8644554e+01, 1.3313127e+02, ..., 2.2617905e+01,
        3.1933162e-01, 5.7496384e-02],
       [7.1178668e-08, 1.2576708e+01, 4.7189323e-07, ..., 2.1200610e+02,
        6.6173779e-05, 1.4676629e+00],
       [4.6852726e-02, 2.4326446e-02, 7.5424228e+00, ..., 3.8855650e-02,
        2.4111785e-01, 3.8122397e-02],
       ...,
       [1.2850331e+00, 7.3023750e-07, 2.3004401e-01, ..., 1.4111414e-07,
        1.8991657e-02, 5.7893607e-07],
       [1.9538748e-10, 1.0852792e+01, 2.5928556e-03, ..., 1.1255099e-02,
        2.2570918e+02, 8.6673790e-06],
       [1.5148736e-02, 5.0508612e-07, 1.2956963e+01, ..., 2.9836469e-06,
        1.0491077e-01, 2.0755589e-04]], dtype=float32)

In [75]:
# digit  디코딩
decoding = np.argmax(y_pred, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0          2
1          7
2          3
3          0
4          3
...      ...
20475      4
20476      2
20477      6
20478      8
20479      6

[20480 rows x 1 columns]

In [76]:
decoding['digit'].unique()

array([2, 7, 3, 0, 6, 8, 1, 4, 9, 5], dtype=int64)

In [77]:
sub = pd.read_csv('data/submission.csv')
sub

id  digit
0       2049      0
1       2050      0
2       2051      0
3       2052      0
4       2053      0
...      ...    ...
20475  22524      0
20476  22525      0
20477  22526      0
20478  22527      0
20479  22528      0

[20480 rows x 2 columns]

In [85]:
sub

id  digit
0       2049      0
1       2050      0
2       2051      0
3       2052      0
4       2053      0
...      ...    ...
20475  22524      0
20476  22525      0
20477  22526      0
20478  22527      0
20479  22528      0

[20480 rows x 2 columns]

In [86]:
sub = sub.drop(['digit'], axis = 1)
sub = pd.concat([sub, decoding], axis = 1)
sub

id  digit
0       2049      2
1       2050      7
2       2051      3
3       2052      0
4       2053      3
...      ...    ...
20475  22524      4
20476  22525      2
20477  22526      6
20478  22527      8
20479  22528      6

[20480 rows x 2 columns]

In [87]:
sub.to_csv('sub.csv', index = False, encoding = 'utf-8')