In [1]:
import tensorflow as tf
import datetime
import keras
import numpy as np
import pandas as pd
from tensorflow.keras import datasets, layers, models, optimizers
%load_ext tensorboard


Using TensorFlow backend.


In [2]:
train = pd.read_csv('data/train.csv')

In [3]:
train

id  digit letter  0  1  2  3  4  5  6  ...  774  775  776  777  778  \
0        1      5      L  1  1  1  4  3  0  0  ...    2    1    0    1    2   
1        2      0      B  0  4  0  0  4  1  1  ...    0    3    0    1    4   
2        3      4      L  1  1  2  2  1  1  1  ...    3    3    3    0    2   
3        4      9      D  1  2  0  2  0  4  0  ...    3    3    2    0    1   
4        5      6      A  3  0  2  4  0  3  0  ...    4    4    3    2    1   
...    ...    ...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
2043  2044      6      V  2  4  3  4  2  4  4  ...    0    2    2    0    0   
2044  2045      1      L  3  2  2  1  1  4  0  ...    2    3    4    2    1   
2045  2046      9      A  4  0  4  0  2  4  4  ...    2    3    1    1    3   
2046  2047      0      Z  2  3  3  0  3  0  4  ...    2    3    1    1    0   
2047  2048      5      Z  4  2  2  1  3  0  0  ...    4    2    4    0    4   

      779  780  781  782  783  
0       4    4    4    3    4  
1       1    4    2    1    2  
2       0    3    0    2    2  
3       4    0    0    1    1  
4       3    4    3    1    2  
...   ...  ...  ...  ...  ...  
2043    1    3    1    4    0  
2044    2    3    4    1    1  
2045    4    2    2    0    0  
2046    4    1    4    3    1  
2047    3    2    4    3    4  

[2048 rows x 787 columns]

In [4]:
aa = train.copy()
aa

id  digit letter  0  1  2  3  4  5  6  ...  774  775  776  777  778  \
0        1      5      L  1  1  1  4  3  0  0  ...    2    1    0    1    2   
1        2      0      B  0  4  0  0  4  1  1  ...    0    3    0    1    4   
2        3      4      L  1  1  2  2  1  1  1  ...    3    3    3    0    2   
3        4      9      D  1  2  0  2  0  4  0  ...    3    3    2    0    1   
4        5      6      A  3  0  2  4  0  3  0  ...    4    4    3    2    1   
...    ...    ...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
2043  2044      6      V  2  4  3  4  2  4  4  ...    0    2    2    0    0   
2044  2045      1      L  3  2  2  1  1  4  0  ...    2    3    4    2    1   
2045  2046      9      A  4  0  4  0  2  4  4  ...    2    3    1    1    3   
2046  2047      0      Z  2  3  3  0  3  0  4  ...    2    3    1    1    0   
2047  2048      5      Z  4  2  2  1  3  0  0  ...    4    2    4    0    4   

      779  780  781  782  783  
0       4    4    4    3    4  
1       1    4    2    1    2  
2       0    3    0    2    2  
3       4    0    0    1    1  
4       3    4    3    1    2  
...   ...  ...  ...  ...  ...  
2043    1    3    1    4    0  
2044    2    3    4    1    1  
2045    4    2    2    0    0  
2046    4    1    4    3    1  
2047    3    2    4    3    4  

[2048 rows x 787 columns]

In [5]:
ytrain = aa['digit']
ytrain = ytrain.to_frame()
ytrain

digit
0         5
1         0
2         4
3         9
4         6
...     ...
2043      6
2044      1
2045      9
2046      0
2047      5

[2048 rows x 1 columns]

In [6]:
xtrain = aa.drop(['id', 'digit', 'letter'], axis = 1)
xtrain

0  1  2  3  4  5  6  7  8  9  ...  774  775  776  777  778  779  780  \
0     1  1  1  4  3  0  0  4  4  3  ...    2    1    0    1    2    4    4   
1     0  4  0  0  4  1  1  1  4  2  ...    0    3    0    1    4    1    4   
2     1  1  2  2  1  1  1  0  2  1  ...    3    3    3    0    2    0    3   
3     1  2  0  2  0  4  0  3  4  3  ...    3    3    2    0    1    4    0   
4     3  0  2  4  0  3  0  4  2  4  ...    4    4    3    2    1    3    4   
...  .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
2043  2  4  3  4  2  4  4  1  2  1  ...    0    2    2    0    0    1    3   
2044  3  2  2  1  1  4  0  1  4  2  ...    2    3    4    2    1    2    3   
2045  4  0  4  0  2  4  4  4  3  4  ...    2    3    1    1    3    4    2   
2046  2  3  3  0  3  0  4  3  0  1  ...    2    3    1    1    0    4    1   
2047  4  2  2  1  3  0  0  0  3  2  ...    4    2    4    0    4    3    2   

      781  782  783  
0       4    3    4  
1       2    1    2  
2       0    2    2  
3       0    1    1  
4       3    1    2  
...   ...  ...  ...  
2043    1    4    0  
2044    4    1    1  
2045    2    0    0  
2046    4    3    1  
2047    4    3    4  

[2048 rows x 784 columns]

In [7]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [8]:
ytrain1 = encoder.fit_transform(ytrain)
ytrain1 = ytrain1.toarray()
ytrain1

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
# digit  디코딩
decoding = np.argmax(ytrain1, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0         5
1         0
2         4
3         9
4         6
...     ...
2043      6
2044      1
2045      9
2046      0
2047      5

[2048 rows x 1 columns]

In [10]:
xtrain /= 255.0

In [11]:
xtrain = np.array(xtrain)
ytrain = np.array(ytrain)

In [12]:
print(xtrain.shape)
print(ytrain.shape)
print(ytrain1.shape)

(2048, 784)
(2048, 1)
(2048, 10)


In [13]:
xtrain = xtrain.reshape((2048, 28, 28, 1))
xtrain = xtrain.astype('float32')
ytrain = ytrain.astype('float32')
ytrain1 = ytrain1.astype('float32')
# ytrain1 = tf.keras.utils.to_categorical(ytrain1, 10)

In [14]:
xtrain.shape

(2048, 28, 28, 1)

In [15]:
ytrain1.shape

(2048, 10)

In [16]:
test = pd.read_csv('data/test.csv')
test = test.drop(['id', 'letter'], axis = 1)
test /= 255
test = np.array(test)
test = test.reshape((20480, 28, 28, 1))
test = test.astype('float32')

In [17]:
test.shape

(20480, 28, 28, 1)

In [18]:
decoding['digit'].unique()

array([5, 0, 4, 9, 6, 8, 1, 3, 2, 7], dtype=int64)

In [19]:
#OPTIMIZER = tf.keras.optimizers.SGD(lr=0.01)
OPTIMIZER = tf.keras.optimizers.Adam(lr = 0.001)

In [20]:
# from tensorflow.keras.preprocessing.image import ImageDataGenerator

# datagen = ImageDataGenerator(
#     rotation_range = 90,
# )
# datagen.fit(xtrain)

In [21]:

def Create_model():

    model = tf.keras.models.Sequential([
        keras.layers.BatchNormalization(input_shape = (28, 28, 1)),
        keras.layers.ZeroPadding2D((1, 1)),
        # keras.layers.Conv2D(64, (5, 5), activation = 'relu', padding = 'same'),
        # keras.layers.BatchNormalization(),
        # keras.layers.Conv2D(64, (3, 3), activation = 'relu'),
        # keras.layers.MaxPooling2D(2, 2),
        # keras.layers.BatchNormalization(),
        keras.layers.Conv2D(64, (5, 5), activation = 'relu', padding = 'same'),
        keras.layers.BatchNormalization(),
        keras.layers.ZeroPadding2D((1, 1)),
        keras.layers.Conv2D(64, (3, 3), activation = 'relu'),
        keras.layers.MaxPooling2D(2, 2),
        #keras.layers.Dropout(0.2),
        keras.layers.BatchNormalization(),
        keras.layers.ZeroPadding2D((1, 1)),
        keras.layers.Conv2D(128, (3, 3), activation = 'relu', padding = 'same'),
        keras.layers.BatchNormalization(),
        keras.layers.ZeroPadding2D((1, 1)),
        keras.layers.Conv2D(128, (3, 3), activation = 'relu'),
        keras.layers.MaxPooling2D(2, 2),
        keras.layers.BatchNormalization(),
        keras.layers.ZeroPadding2D((1, 1)),
        keras.layers.Conv2D(256, (3, 3), activation = 'relu'),
        keras.layers.BatchNormalization(),
        keras.layers.ZeroPadding2D((1, 1)),
        keras.layers.Conv2D(256, (3, 3), activation = 'relu'),
        keras.layers.MaxPooling2D(2, 2),
        keras.layers.Dropout(0.2),
        keras.layers.Flatten(),
        keras.layers.BatchNormalization(),
        keras.layers.Dense(1000, activation = 'relu'),
        keras.layers.Dropout(0.5),
        keras.layers.BatchNormalization(),
        keras.layers.Dense(10, activation = 'softmax')
    ])

    model.compile(optimizer = OPTIMIZER,
                  loss = 'categorical_crossentropy',
                  metrics = ["accuracy"])

    return model

model = Create_model()
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization (BatchNo (None, 28, 28, 1)         4         
_________________________________________________________________
zero_padding2d (ZeroPadding2 (None, 30, 30, 1)         0         
_________________________________________________________________
conv2d (Conv2D)              (None, 30, 30, 64)        1664      
_________________________________________________________________
batch_normalization_1 (Batch (None, 30, 30, 64)        256       
_________________________________________________________________
zero_padding2d_1 (ZeroPaddin (None, 32, 32, 64)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 30, 30, 64)        36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 64)        0

In [22]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
checkpoint = tf.keras.callbacks.ModelCheckpoint('best_model.h5', save_weights_only=True, save_best_only=True)


In [23]:
# checkpoint = ModelCheckpoint(
#     'best_model.h5',
#     monitor = 'val_loss',
#     verbose = 1,
#     save_best_only = True,
#     save_weights_only = True,
#     mode = 'auto'
# )

In [24]:
log_dir = "logs/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard = tf.keras.callbacks.TensorBoard(log_dir = log_dir, histogram_freq = 1)
# model.fit_generator(
#     datagen.flow(xtrain, ytrain1, batch_size = 32),
#     epochs = 150,
#     verbose = 1,
#     callbacks = [tensorboard, checkpoint]
# )
model.fit(xtrain, ytrain1,
          batch_size = 26,
          epochs = 30,
          verbose = 1,
          validation_split = 0.10,
          callbacks = [checkpoint, tensorboard])

%tensorboard --logdir logs

Epoch 1/30
71/71 [==============================] - 14s 190ms/step - loss: 2.3587 - accuracy: 0.3033 - val_loss: 12.5015 - val_accuracy: 0.0976
Epoch 2/30
71/71 [==============================] - 14s 193ms/step - loss: 1.5517 - accuracy: 0.4976 - val_loss: 14.7951 - val_accuracy: 0.0976
Epoch 3/30
71/71 [==============================] - 13s 182ms/step - loss: 1.1228 - accuracy: 0.6370 - val_loss: 14.4207 - val_accuracy: 0.0976
Epoch 4/30
71/71 [==============================] - 13s 178ms/step - loss: 0.8516 - accuracy: 0.7222 - val_loss: 11.6741 - val_accuracy: 0.0976
Epoch 5/30
71/71 [==============================] - 14s 194ms/step - loss: 0.6073 - accuracy: 0.7868 - val_loss: 6.7880 - val_accuracy: 0.1073
Epoch 6/30
71/71 [==============================] - 14s 200ms/step - loss: 0.5464 - accuracy: 0.8117 - val_loss: 5.0545 - val_accuracy: 0.1756
Epoch 7/30
71/71 [==============================] - 13s 186ms/step - loss: 0.4166 - accuracy: 0.8600 - val_loss: 2.8055 - val_accuracy: 0.

Reusing TensorBoard on port 6006 (pid 20600), started 1 day, 8:08:03 ago. (Use '!kill 20600' to kill it.)

[Tensorboard Link](http://localhost:6006)  
71/71 [==============================] - 13s 181ms/step - loss: 0.0737 - accuracy: 0.9756 - val_loss: 0.5013 - val_accuracy: 0.8244

In [25]:
y_pred = model.predict(test, batch_size=32)
# digit  디코딩
decoding = np.argmax(y_pred, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0          6
1          9
2          3
3          0
4          3
...      ...
20475      4
20476      1
20477      6
20478      1
20479      0

[20480 rows x 1 columns]

In [26]:
decoding['digit'].unique()

array([6, 9, 3, 0, 5, 4, 1, 7, 2, 8], dtype=int64)

In [27]:
model.load_weights('best_model.h5')
y_pred = model.predict(test, batch_size=26)
# digit  디코딩
decoding = np.argmax(y_pred, axis=1).reshape(-1,1)
decoding = pd.DataFrame(decoding, columns = ['digit'])
decoding

digit
0          6
1          9
2          8
3          0
4          3
...      ...
20475      4
20476      1
20477      6
20478      1
20479      0

[20480 rows x 1 columns]

In [28]:
sub = pd.read_csv('data/submission.csv')
sub = sub.drop(['digit'], axis = 1)
sub = pd.concat([sub, decoding], axis = 1)
sub.to_csv('sub.csv', index = False, encoding = 'utf-8')
sub

id  digit
0       2049      6
1       2050      9
2       2051      8
3       2052      0
4       2053      3
...      ...    ...
20475  22524      4
20476  22525      1
20477  22526      6
20478  22527      1
20479  22528      0

[20480 rows x 2 columns]