In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')
sub = pd.read_csv('data/submission.csv')

In [33]:
train_copy = train.copy()

In [20]:
object_column = ['letter']
train[object_column] = train[object_column].apply(lambda x : x.astype('category').cat.codes)

In [22]:
label = train['digit']
label

0       5
1       0
2       4
3       9
4       6
       ..
2043    6
2044    1
2045    9
2046    0
2047    5
Name: digit, Length: 2048, dtype: int64

In [32]:
letter = train['letter']
letter

0       11
1        1
2       11
3        3
4        0
        ..
2043    21
2044    11
2045     0
2046    25
2047    25
Name: letter, Length: 2048, dtype: int8

In [38]:
train_copy = train_copy.drop(['id', 'digit', 'letter'], axis = 1)
train_copy

0  1  2  3  4  5  6  7  8  9  ...  774  775  776  777  778  779  780  \
0     1  1  1  4  3  0  0  4  4  3  ...    2    1    0    1    2    4    4   
1     0  4  0  0  4  1  1  1  4  2  ...    0    3    0    1    4    1    4   
2     1  1  2  2  1  1  1  0  2  1  ...    3    3    3    0    2    0    3   
3     1  2  0  2  0  4  0  3  4  3  ...    3    3    2    0    1    4    0   
4     3  0  2  4  0  3  0  4  2  4  ...    4    4    3    2    1    3    4   
...  .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
2043  2  4  3  4  2  4  4  1  2  1  ...    0    2    2    0    0    1    3   
2044  3  2  2  1  1  4  0  1  4  2  ...    2    3    4    2    1    2    3   
2045  4  0  4  0  2  4  4  4  3  4  ...    2    3    1    1    3    4    2   
2046  2  3  3  0  3  0  4  3  0  1  ...    2    3    1    1    0    4    1   
2047  4  2  2  1  3  0  0  0  3  2  ...    4    2    4    0    4    3    2   

      781  782  783  
0       4    3    4  
1       2    1    2  
2       0    2    2  
3       0    1    1  
4       3    1    2  
...   ...  ...  ...  
2043    1    4    0  
2044    4    1    1  
2045    2    0    0  
2046    4    3    1  
2047    4    3    4  

[2048 rows x 784 columns]

In [59]:
train_array = np.array(train_copy)
label_array = np.array(label)
letter_array = np.array(letter) 

In [47]:
train_array

array([[1, 1, 1, ..., 4, 3, 4],
       [0, 4, 0, ..., 2, 1, 2],
       [1, 1, 2, ..., 0, 2, 2],
       ...,
       [4, 0, 4, ..., 2, 0, 0],
       [2, 3, 3, ..., 4, 3, 1],
       [4, 2, 2, ..., 4, 3, 4]], dtype=int64)

In [62]:
aa = np.array([train_copy, letter])
aa

array([      0  1  2  3  4  5  6  7  8  9  ...  774  775  776  777  778  779  780  \
0     1  1  1  4  3  0  0  4  4  3  ...    2    1    0    1    2    4    4   
1     0  4  0  0  4  1  1  1  4  2  ...    0    3    0    1    4    1    4   
2     1  1  2  2  1  1  1  0  2  1  ...    3    3    3    0    2    0    3   
3     1  2  0  2  0  4  0  3  4  3  ...    3    3    2    0    1    4    0   
4     3  0  2  4  0  3  0  4  2  4  ...    4    4    3    2    1    3    4   
...  .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
2043  2  4  3  4  2  4  4  1  2  1  ...    0    2    2    0    0    1    3   
2044  3  2  2  1  1  4  0  1  4  2  ...    2    3    4    2    1    2    3   
2045  4  0  4  0  2  4  4  4  3  4  ...    2    3    1    1    3    4    2   
2046  2  3  3  0  3  0  4  3  0  1  ...    2    3    1    1    0    4    1   
2047  4  2  2  1  3  0  0  0  3  2  ...    4    2    4    0    4    3    2   

      781  782  783  
0       4    3    4  
1       2   

In [68]:
letter.nunique()

26

In [52]:
label_array.shape[0]

2048

In [45]:
train_array.shape

(2048, 784)

In [ ]:
X_train = np.array(t)

In [29]:
aa = train.describe().T
aa

count         mean         std  min     25%     50%      75%     max
id      2048.0  1024.500000  591.350996  1.0  512.75  1024.5  1536.25  2048.0
digit   2048.0     4.440918    2.819159  0.0    2.00     4.0     7.00     9.0
letter  2048.0    12.722168    7.453517  0.0    6.00    13.0    19.00    25.0
0       2048.0     2.031250    1.420762  0.0    1.00     2.0     3.00     4.0
1       2048.0     1.959961    1.399057  0.0    1.00     2.0     3.00     4.0
...        ...          ...         ...  ...     ...     ...      ...     ...
779     2048.0     2.043457    1.407484  0.0    1.00     2.0     3.00     4.0
780     2048.0     2.035156    1.399886  0.0    1.00     2.0     3.00     4.0
781     2048.0     1.981445    1.409247  0.0    1.00     2.0     3.00     4.0
782     2048.0     1.993164    1.392264  0.0    1.00     2.0     3.00     4.0
783     2048.0     1.975586    1.398719  0.0    1.00     2.0     3.00     4.0

[787 rows x 8 columns]

In [31]:
aa['max'].unique()

array([2048.,    9.,   25.,    4.,    6.,   20.,   10.,   21.,   58.,
         22.,   50.,  104.,  108.,   72.,   66.,   63.,  105.,   61.,
         18.,   17.,  124.,  101.,  125.,  123.,  126.,  163.,  145.,
        142.,  181.,  166.,  172.,  208.,  209.,  213.,  243.,  225.,
        232.,  201.,  202.,  164.,  165.,  137.,  109.,   32.,  131.,
        168.,  255.,  235.,  246.,  252.,  253.,  221.,  226.,  130.,
         62.,  136.,  230.,  244.,  254.,  240.,  198.,   56.,  139.,
        251.,  250.,  247.,  176.,   96.,   65.,  178.,  234.,  186.,
         44.,  128.,  167.,  249.,  216.,  122.,  190.,  129.,   13.,
        127.,   64.,  239.,  236.,   29.,  211.,   36.,  199.,   43.,
         31.,  223.,   28.,  238.,  140.,  188.,  233.,   54.,  174.,
        157.,   40.,  171.,  113.,   19.,   67.,  149.,  245.,  248.,
        229.,  237.,  242.,  203.,  217.,  100.,   16.,  144.,  187.,
        183.,  184.,  197.,  215.,  169.,  150.,  219.,  147.,  155.,
        138.,   86.,

In [4]:
28*28

784

In [5]:
test

id letter  0  1  2  3  4  5  6  7  ...  774  775  776  777  778  \
0       2049      L  0  4  0  2  4  2  3  1  ...    2    0    4    2    2   
1       2050      C  4  1  4  0  1  1  0  2  ...    0    3    2    4    2   
2       2051      S  0  4  0  1  3  2  3  0  ...    1    3    2    0    3   
3       2052      K  2  1  3  3  3  4  3  0  ...    3    0    3    2    4   
4       2053      W  1  0  1  1  2  2  1  4  ...    4    3    1    4    0   
...      ...    ... .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...   
20475  22524      P  1  2  1  1  0  0  0  2  ...    0    1    3    0    3   
20476  22525      S  4  1  1  4  0  0  1  1  ...    1    3    1    0    0   
20477  22526      B  4  2  1  3  2  1  3  0  ...    3    2    3    4    1   
20478  22527      K  1  1  2  3  4  0  4  3  ...    2    0    0    4    3   
20479  22528      S  2  1  0  3  0  3  3  1  ...    0    3    0    1    4   

       779  780  781  782  783  
0        4    3    4    1    4  
1        4    2    2    1    2  
2        2    3    0    1    4  
3        1    0    4    4    4  
4        2    1    2    3    4  
...    ...  ...  ...  ...  ...  
20475    0    4    3    1    4  
20476    1    3    1    2    0  
20477    0    3    3    1    1  
20478    3    3    4    4    2  
20479    2    0    2    2    0  

[20480 rows x 786 columns]

In [6]:
sub

id  digit
0       2049      0
1       2050      0
2       2051      0
3       2052      0
4       2053      0
...      ...    ...
20475  22524      0
20476  22525      0
20477  22526      0
20478  22527      0
20479  22528      0

[20480 rows x 2 columns]

In [7]:
tf.__version__

'2.2.0'

In [8]:
mnist = keras.datasets.mnist
(X_train, Y_train),(X_test, Y_test) = mnist.load_data()

In [9]:
X_train.shape

(60000, 28, 28)

In [10]:
train.values

array([[1, 5, 'L', ..., 4, 3, 4],
       [2, 0, 'B', ..., 2, 1, 2],
       [3, 4, 'L', ..., 0, 2, 2],
       ...,
       [2046, 9, 'A', ..., 2, 0, 0],
       [2047, 0, 'Z', ..., 4, 3, 1],
       [2048, 5, 'Z', ..., 4, 3, 4]], dtype=object)

In [11]:
train.iloc[0].unique()

array([1, 5, 'L', 4, 3, 0, 2, 16, 73, 51, 21, 108, 176, 249, 190, 128,
       133, 188, 207, 107, 96, 119, 137, 28, 31, 123, 62, 46, 126, 66, 6,
       65, 127, 67, 120, 44, 22, 106, 112, 102, 130, 114, 19, 143, 200,
       150, 24, 10, 240, 220, 166, 217, 142, 116, 68, 129, 37, 131, 105,
       18, 69, 132, 76, 23, 86, 172, 181, 125, 235, 237, 70, 101, 98, 30,
       7], dtype=object)

In [12]:
train.iloc[1].unique()

array([2, 0, 'B', 4, 1, 3, 11, 56, 21, 123, 81, 14, 18, 126, 108, 22, 111,
       129, 113, 35, 133, 157, 101, 25, 143, 192, 130, 44, 189, 234, 147,
       102, 236, 253, 183, 248, 255, 186, 92, 146, 251, 238, 74, 63, 239,
       174, 137, 125, 119, 69, 6, 136, 213, 131, 128, 127, 122, 48, 110,
       73, 41, 46, 86, 116, 34, 10, 105, 167, 115, 42, 5, 15, 114, 88, 89,
       154, 72, 141, 170, 117, 148, 59, 144, 235, 184, 175, 177, 132, 53,
       197, 67, 145, 212, 218, 164, 26, 220, 84, 199, 249, 227, 155, 104,
       79, 254, 242, 216, 190, 160, 142, 103, 90, 99, 65, 250, 245, 240,
       228, 211, 168, 140, 58, 100, 83, 151, 139, 124, 17, 45, 64, 60, 28],
      dtype=object)

In [13]:
X_train.shape

(60000, 28, 28)

In [14]:
aa = X_train.reshape(60000, 28 * 28)

In [15]:
aa.shape

(60000, 784)

In [17]:
X_test.shape

(10000, 28, 28)

In [19]:
Y_train.shape

(60000,)

In [70]:
from tensorflow.keras import datasets
(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

In [ ]:
X_train = X_train.reshape((60000,))